#!/bin/bash

if [ -z $1 ]; then
    echo "Must provide the username"
    exit 1
fi
if [ -z $2 ]; then
    echo "Must provide the user's password"
    exit 1
fi

if [[ $1 =~ ^[0-9a-zA-Z_]+$  ]]; then
    echo "Invalid string format for username: Must be alphnumeric."
    exit 2
fi
if [[ ! $1 =~ ^[a-zA-Z]{1}[0-9a-zA-Z\$\#%@!_]+$ ]]; then
    echo "Invalid string format for password: Must be alphnumeric and only certain symbols allowed (#@!_%)."
    exit 2
fi

mysql -u root -p$(echo $MYSQL_ROOT_PASSWORD) -e "create user '$1'@'%' identified by '$2';"

exit 0

