#!/bin/bash

if [ -z $1 ]; then
    echo "Must provide the database name, and name the .sql file <db name>_schema.sql"
    exit 1
fi
if [[ ! $1 =~ ^[0-9a-zA-Z\$_]+$  ]]; then
    echo "Invalid string format for database: Must be alphnumeric."
    exit 2
fi

# Pass in the filename as 2nd param, otherwise its name is assumed to match the
# db-name and be suffixed "_schema.sql"
PATH=${2-/db-imports/$1_schema.sql}

if [ ! -f "$PATH"  ]; then
    echo "Import file $PATH does not exist"
    exit 1
fi

# Optionally, you can import from a compressed *.sql.gz archive
if [[ "$PATH" == *.sql.gz ]]; then
    /usr/bin/gunzip < $PATH | /usr/bin/mysql -u root -p$(echo $MYSQL_ROOT_PASSWORD) $1
else
    /usr/bin/mysql -u root -p$(echo $MYSQL_ROOT_PASSWORD) $1 < $PATH
fi

exit 0

