#!/bin/bash

if [ -z $1 ]; then
    echo "Must provide the database name"
    exit 1
fi
if [ -z $2 ]; then
    echo "Must provide the table name"
    exit 1
fi
if [[ $1 =~ ^[0-9a-zA-Z\$_]+$  ]]; then
    echo "Invalid string format for database: Must be alphnumeric."
    exit 2
fi
if [[ $2 =~ ^[0-9a-zA-Z\$_]+$  ]]; then
    echo "Invalid string format for table name: Must be alphnumeric."
    exit 2
fi

mysqlshow -u root -p$(echo $MYSQL_ROOT_PASSWORD) --keys $1 $2

exit 0

